pool:
  vmImage: $(imageName)

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        py311:
          PYTHON_VERSION: 3.11
        py312:
          PYTHON_VERSION: 3.12
        py313:
          PYTHON_VERSION: 3.13
        py314:
          PYTHON_VERSION: 3.14
    steps:
      - script: bash ci/build_unix.sh
  - job: lint
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: bash run_lint.sh
  - job: OSX
    pool:
      vmImage: macOS-latest
    strategy:
      matrix:
        py310:
          PYTHON_VERSION: 3.10
    steps:
      # Conda was removed from macos vmImages 13 and 14
      - script: |
          CONDA=~/conda
          curl -fsSLo Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-$(uname -m).sh"
          bash Miniforge3.sh -b -p "${CONDA}"
          rm Miniforge3.sh
          source "${CONDA}/etc/profile.d/conda.sh"
          echo "##vso[task.setvariable variable=CONDA]$CONDA";
        displayName: Install miniforge in runner
      - bash: echo "##vso[task.prependpath]~/conda/bin"
        displayName: Add conda to PATH
      - bash: |
          sudo xcode-select -s /Applications/Xcode_13.2.1.app
          bash ci/build_unix.sh
  - job: Windows
    pool:
      vmImage: windows-2022
    strategy:
      matrix:
        windows_py310:
          PYTHON_VERSION: 3.10
    steps:
      # https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=windows
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH
      - script: ci/build_windows.bat
