pool:
  vmImage: $(imageName)

jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        py311:
          PYTHON_VERSION: 3.11
        py312:
          PYTHON_VERSION: 3.12
    steps:
      - script: bash ci/build_unix.sh
  - job: OSX
    pool:
      vmImage: macOS-latest
    strategy:
      matrix:
        py310:
          PYTHON_VERSION: 3.10
    steps:
      - script: |
          sudo xcode-select -s /Applications/Xcode_13.2.1.app
          bash ci/build_unix.sh
  - job: Windows
    pool:
      vmImage: windows-2019
    strategy:
      matrix:
        windows_py310:
          PYTHON_VERSION: 3.10
    steps:
      # https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=windows
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH
      - script: ci/build_windows.bat
